GET http://127.0.0.1:8000


###
GET http://127.0.0.1:8001/get


###
POST http://127.0.0.1:8002/predict
Content-Type: application/json

{
    "service_provider": "AIRTEL",
    "network_type": "3G",
    "start_loc": "Delhi",
    "end_loc": "Delhi"
}